modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "assets/${mod_id}/logo.png"
description = '''${mod_description}'''
authors = "Bawnorton"
issueTrackerURL = "https://github.com/Bawnorton/${mod_name}/issues"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"

[[dependencies.${mod_id}]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.6.0,)"

[[dependencies.${mod_id}]]
modId = "tacz"
mandatory = true
versionRange = "[1.1.6-hotfix,)"